name: "ios"


on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    name: "ios"
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

#    - name: Setup interactive tmate session
#      uses: mxschmitt/action-tmate@v3

    - name: Clone imgui_bundle
      run: |
        mkdir -p external && cd external
        git clone https://github.com/pthom/imgui_bundle.git
        cd imgui_bundle && git submodule update --init --recursive && cd ..
        cd ..

    - name: CMake
      run: |
        mkdir build-ios
        cd build-ios
        cmake .. \
          -GXcode \
          -DCMAKE_TOOLCHAIN_FILE=../external/imgui_bundle/external/hello_imgui/hello_imgui/hello_imgui_cmake/ios-cmake/ios.toolchain.cmake \
          -DPLATFORM=SIMULATOR64

    - name: Build for simulator
      working-directory: build-ios
      run: |
        xcodebuild -configuration Release -project imgui_bundle_example_integration.xcodeproj -target ALL_BUILD -arch x86_64 -sdk iphonesimulator
